---
- name: Install packages (Debian).
  sudo: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items: mantis_packages
  when: ansible_os_family == 'Debian'

- name: Install python-mysqldb (Debian).
  sudo: yes
  apt:
    name: python-mysqldb
  when: mantis_create_db
