---
- name: Download Mantis.
  get_url:
    url: "http://sourceforge.net/projects/mantisbt/files/mantis-stable/{{ mantis_version }}/mantisbt-{{ mantis_version }}.{{ mantis_file_extension }}/download"
    dest: "{{ mantis_tmp }}"
  register: mantis_downloaded

- name: Create directory for Mantis.
  sudo: yes
  file:
    path: "{{ mantis_path }}"
    state: directory
  when: mantis_downloaded.changed

- name: Extract Mantis.
  sudo: yes
  unarchive:
    src: "{{ mantis_tmp }}"
    dest: "{{ mantis_path }}"
    copy: no
    mode: 0755
    owner: root
    group: root
  when: mantis_downloaded.changed

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages.
  sudo: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items: mantis_packages

- name: Start services.
  sudo: yes
  service:
    name: "{{ item }}"
    state: running
    enabled: true
  with_items: mantis_services

- name: Create Mantis vhost.
  sudo: yes
  template:
    src: vhost.j2
    dest: "{{ mantis_vhost_dir }}/mantis.conf"
  notify: restart apache
  when: mantis_install_vhost

- name: Install python-mysqldb
  sudo: yes
  apt:
    name: python-mysqldb
  when: mantis_create_db

- name: Create Mantis database.
  sudo: yes
  mysql_db:
    name: "{{ mantis_db_name }}"
    state: present
  when: mantis_create_db
  register: mantis_db_created

- name: Copy database install script.
  copy:
    src: install.sql
    dest: /tmp/mantis_install.sql
  when: mantis_install_db

- name: Install Mantis database.
  sudo: yes
  mysql_db:
    name: "{{ mantis_db_name }}"
    state: import
    target: /tmp/mantis_install.sql
  when: mantis_db_created.changed

- name: Create Mantis database user.
  sudo: yes
  mysql_user:
    name: "{{ mantis_db_user }}"
    password: "{{ mantis_db_pass }}"
    priv: "{{ mantis_db_name }}.*:ALL"
    state: present
  when: mantis_install_db

- name: Copy config_inc.php
  sudo: yes
  template:
    src: config_inc.php.j2
    dest: "{{ mantis_full_path }}/config_inc.php"
    mode: 0755
    owner: root
    group: root

- name: Remove admin directory.
  file:
    path: "{{ mantis_full_path }}/admin"
    state: absent
  when: mantis_remove_admin
