---
- name: Install packages (RedHat).
  sudo: yes
  yum:
    name: "{{ item }}"
    state: installed
  with_items: mantis_packages
  when: ansible_os_family == 'RedHat'

- name: Install MySQL-python (RedHat)
  sudo: yes
  yum:
    name: MySQL-python
  when: mantis_create_db
